version: '2'

services:

  redis:
    restart: always
    image: redis

  django:
    restart: always
    build:
      context: backend
    command: gunicorn website.wsgi:application -b :8082 --reload
    links:
      - redis
      - rqworker
    depends_on:
      - redis
      - rqworker
    volumes:
      - ./backend:/code

  rqworker:
    restart: always
    build: backend
    command: ./rqworker_reload.sh
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./backend:/code

  vue:
    restart: always
    build: frontend
    command: npm run dev
    volumes:
      - ./frontend:/code
      - /code/node_modules
      - /code/dist

  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    links:
      - vue
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.template
      - /var/log/nginx_cuba:/var/log/nginx
    environment:
     - BUFFERING=off
    command: /bin/bash -c "envsubst '$$BUFFERING' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
