version: '2'

services:
  django:
    environment:
      - DEBUG=False

  rqworker:
    environment:
      - DEBUG=False

  vue:
    command: ./production_server.sh

  nginx:
    environment:
      - BUFFERING=on
